version: '3.7'

services:
  web:
    build:
      context: .
    container_name: scinav_web
    command: ["./wait-for-postgres.sh", "db", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://your_db_user:your_db_password@db/your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name

  db:
    image: postgres:13
    container_name: scinav_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"

  alembic:
    build:
      context: .
    container_name: scinav_alembic
    working_dir: /app
    volumes:
      - .:/app
    command: ["./wait-for-postgres.sh", "db", "alembic upgrade head"]
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://your_db_user:your_db_password@db/your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: scinav_client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - web

volumes:
  postgres_data:
